### ISSUE TITLE
zlm、wvp部署在同一云服务器上时点播超时。

### ISSUE THREAD

**Issue by Imqzef** [648540858/wvp-GB28181-pro#117]
### 问题描述
``` 
1.zlm、wvp部署在同一云服务器上点播超时。
2.设置rtp:enable:false后还是点播超时。
```
### 配置
```
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -fflags nobuffer -rtsp_transport tcp -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
enableVhost=0
enable_audio=1
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=thmj0cjmrJmjDTco
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=18000
ts_demand=0

[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
enable=1
on_flow_report=
on_http_access=
on_play=http://127.0.0.1:55566/index/hook/on_play
on_publish=http://127.0.0.1:55566/index/hook/on_publish
on_record_mp4=
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_server_started=http://127.0.0.1:55566/index/hook/on_server_started
on_shell_login=http://127.0.0.1:55566/index/hook/on_shell_login
on_stream_changed=http://127.0.0.1:55566/index/hook/on_stream_changed
on_stream_none_reader=http://127.0.0.1:55566/index/hook/on_stream_none_reader
on_stream_not_found=http://127.0.0.1:55566/index/hook/on_stream_not_found
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
keepAliveSecond=15
maxReqSize=4096
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit-5.0(build in Jun 25 2021 17:07:06)</center></body></html>
port=55568
rootPath=./www
sendBufSize=65536
sslport=55569

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=55570
sslport=55571

[rtp]
audioMtuSize=600
videoMtuSize=1400

[rtp_proxy]
dumpDir=
port=55572
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=55573
sslport=55574

[shell]
maxReqSize=1024
port=9000

; } ---
```
```
spring:
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 6
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: ''
    # [可选] 超时时间
    timeout: 10000
  # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
  datasource:
    name: wvp
    url: jdbc:mysql://127.0.0.1:3306/wvp?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    # 打包为jar运行时把wvp.sqlite发到jar同级文件夹，同时url改为：
    # url: jdbc:sqlite:wvp.sqlite
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:   com.mysql.cj.jdbc.Driver
    max-active: 1
    min-idle: 1
# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 55566
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:xxx.jks
    # [可选] 证书密码
    key-password: password
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS
# 作为28181服务器的配置
sip:
  # monitorIp: 172.17.48.211
  # [必须修改] 本机的IP,网卡IP
  ip: 172.17.48.211
  # [可选] 28181服务监听的端口
  port: 55567
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 44030550031322010002
  # [可选]
  id: 44030550031322010001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: admin123
#zlm 默认服务器配置
media:
  # [必须修改] zlm服务器的内网IP
  ip: 127.0.0.1
  wanIp: 公网IP # zlm所在服务器的公网IP
  streamIp: 公网IP 
  hookIp: 127.0.0.1
  # [必须修改] zlm服务器的http.port
  httpPort: 55568
  # [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
  autoConfig: true
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: false
    # [可选] 在此范围内选择端口用于媒体流传输,
    portRange: 55575,55585 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  recordAssistPort: 0
# [可选] 日志配置, 一般不需要改
logging:
  file:
    name: logs/wvp.log
    max-history: 30
    max-size: 10MB
    total-size-cap: 300MB
  level:
    com:
      genersoft:
        iot: info
# [根据业务需求配置]
userSettings:
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  autoApplyPlay: false
  # 是否开启接口鉴权
  interfaceAuthentication: true
  # 推流直播是否录制
  recordPushLive: true
# 在线文档： swagger-ui（生产环境建议关闭）
springfox:
  documentation:
    swagger-ui:
      enabled: true
```
### ZLM日志
1.设置rtp:enable:true
![1624935200(1)](https://user-images.githubusercontent.com/39127838/123730372-d3004080-d8c8-11eb-85c5-964a6c5021df.jpg)
2.设置rtp:enable:false
![1624935424(1)](https://user-images.githubusercontent.com/39127838/123730703-68033980-d8c9-11eb-9cdc-f65d426cbd85.jpg)
