### ISSUE TITLE
通道数为0，刷新超时

### ISSUE THREAD

**Issue by HugoPu** [648540858/wvp-GB28181-pro#1327]
**环境信息:**

 - 1. 部署方式： wvp-pro / zlm(docker) 
 - 2. 部署环境： windows10
 - 3. 端口开放情况：全部
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康
 - 7. 你做过哪些尝试：下载最新代码
 - 8. 代码更新时间：2024/2/27

**内容描述:**
设备列表显示有设备，但通道数为0，点击刷新显示超时，抓包发现没有从wvp发出到设备的包，都是设备到wvp服务器的
配置如下：
```
# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
  # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
  # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
  ip: 10.32.133.50
  # [可选] 28181服务监听的端口
  port: 8116
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 3402000000
  # [可选]
  id: 34020000002000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  # password: bajiuwulian1006
  # 是否存储alarm信息
  alarm: true
```
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/22905948/3d2f4d4d-ff2f-4492-b788-b262a037d538)

**抓包文件**
  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/22905948/37ff9d0d-1b2f-4ee6-9b9c-89121c519630)

**日志**
```
日志内容放这里， 文件的话请直接上传
```
