### ISSUE TITLE
技术咨询：推流成功后，推流列表不显示，其他功能列表也不显示.

### ISSUE THREAD

**Issue by CaiJinHao** [648540858/wvp-GB28181-pro#1580]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况
0976c67f70eb   wvp-gb28181-pro-wvp   "sh run.sh"              2 hours ago    Up 2 hours    0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:554->554/tcp, :::554->554/tcp, 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:5060->5060/tcp, 0.0.0.0:5060->5060/udp, :::5060->5060/tcp, :::5060->5060/udp, 0.0.0.0:10000->10000/tcp, :::10000->10000/tcp, 0.0.0.0:18080-18081->18080-18081/tcp, 0.0.0.0:10000->10000/udp, :::18080-18081->18080-18081/tcp, :::10000->10000/udp, 0.0.0.0:30000-30500->30000-30500/tcp, :::30000-30500->30000-30500/tcp, 554/udp, 0.0.0.0:30000-30500->30000-30500/udp, :::30000-30500->30000-30500/udp, 6379/tcp   wvp-gb28181-pro-wvp-1
 - 4. 是否是公网部署 
否
 - 5. 是否使用https
否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 -2024.8.16

** 相关配置** 
```
# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
    # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
    # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
    # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
    ip: ${WVP_HOST:0.0.0.0}
    # [可选] 28181服务监听的端口
    port: ${WVP_PORT:5060}
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: ${WVP_DOMAIN:3402000000}
    # [可选]
    id: ${WVP_ID:34020000002000000001}
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: ${WVP_PWD:admin123}
```

#zlm 默认服务器配置
```
media:
    # [必须修改] zlm服务器唯一id，用于触发hook时区别是哪台服务器,general.mediaServerId
    id: d9eb2d1925cc
    # [必须修改] zlm服务器的内网IP
    ip: ${ZLM_HOST:0.0.0.0}
    # [必须修改] zlm服务器的http.port
    http-port: ${ZLM_PORT:80}
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 18081
    sdp-ip: ${sip.ip:0.0.0.0}
    stream-ip: ${sip.ip:0.0.0.0}
```
**内容描述:**
推流使用 ffmpeg-python 
import ffmpeg
# 创建 FFmpeg 流
process = (
    ffmpeg
    .input('pipe:0', format='rawvideo', pix_fmt='bgr24', s=f'{width}x{height}', r=fps)
    .output(rtmp_url, format='flv', video_bitrate='5000k')
    .run_async(pipe_stdin=True)
)
process.stdin.write(frame.tobytes())

**截图**  
推流截图  推流地址：rtmp://172.30.180.228/test/live
![image](https://github.com/user-attachments/assets/21c229bc-a591-4ff8-a08c-f1f999e36f55)
播放截图 播放地址：rtmp://172.30.180.228/test/live?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
![image](https://github.com/user-attachments/assets/a1c54b29-384c-408e-a784-53d62738e8fd)

**抓包文件**
  
**日志**
```
无日志
在推流之前我将挂载的logs文件下的日志全部删除掉了。推流成功之后没有任何日志
```
