### ISSUE TITLE
【技术咨询】7*24小时录像，如何设置时长，云端录像如何合并下载？

### ISSUE THREAD

**Issue by Oushinan** [648540858/wvp-GB28181-pro#1614]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos 
 - 3. 端口开放情况：内网
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间 2024/9/5

**内容描述:**
1. 使用7*24小时不间断录像方案，录像的大小都是24s，如何设置时长，看到ZLMediaServer有个配置参数，mp4_max_second，配置的是3600，但是看起来并没有用。

2. 使用了wvp-pro-assist，但是云端录像界面没有合并下载等按钮，时间显示也是有问题的。

**截图**  
![image](https://github.com/user-attachments/assets/3c116b01-07b0-4eee-84da-4dd3236b3868)
![image](https://github.com/user-attachments/assets/77133daf-eb60-45ee-aa71-f458d634105e)
![image](https://github.com/user-attachments/assets/73bee9d3-6c88-48da-923f-344a9f2f754f)

**抓包文件**
  
**日志**
```
wvp的部分配置文件
#zlm 默认服务器配置
media:
  # [必须修改] zlm服务器的id config.ini中的mediaServerId
  id: ccitIoTMediaServer
  # [必须修改] zlm服务器的内网IP
  ip: 10.10.25.165
  # [可选] 有公网IP就配置公网IP, 不可用域名
  wan_ip:
  # [必须修改] zlm服务器的http.port
  http-port: 50000
  # [可选] 返回流地址时的ip，置空使用 media.ip
  stream-ip: 10.10.25.165
  # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
  sdp-ip: 10.10.25.165
  # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
  hook-ip: 10.10.25.165
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 443
  # [必选] zlm服务器的hook.admin_params=secret
  secret: abTC0O9SOhvDP74TYTAcZ1sSSZQtBsTi
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 50001,50300 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 50000,50300 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  record-assist-port: 18081
  # 录像路径
  record-path: /home/record
  # 录像保存时长
  record-day: 7
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
# [根据业务需求配置]
user-settings:
  server-id: 111111
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 180000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 设备/通道状态变化时发送消息
  device-status-notify: true
  # 推流直播是否录制
  record-push-live: true
  # 国标是否录制
  record-sip: true
  # 是否开启sip日志
  sip-log: false
  # 等待音视频编码信息再返回， true： 可以根据编码选择合适的播放器，false： 可以更快点播
  wait-track: true
  # 国标点播 按需拉流, true：有人观看拉流，无人观看释放， false：拉起后不自动释放
  stream-on-demand: false
# [可选] 日志配置, 一般不需要改


assist的配置文件
server:
    port: 18081
    # [可选] HTTPS配置， 默认不开启
    ssl:
        # [可选] 是否开启HTTPS访问
        enabled: false
        # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
        key-store: classpath:xxx.jks
        # [可选] 证书密码
        key-password: password
        # [可选] 证书类型， 默认为jks，根据实际修改
        key-store-type: JKS

# [根据业务需求配置]
userSettings:
    id: 111111
    # [可选 ] 临时录像路径
    record-temp: /home/media/record
    # [可选 ] 录像保存时长（单位： 天）每天晚12点自动对过期文件执行清理, 不配置则不删除
    record-temp-day: 7
    # [可选 ] 录像下载合成临时文件保存时长， 不配置默认取值recordDay（单位： 天）每天晚12点自动对过期文件执行清理
    # recordTempDay: 7
    # [必选 ] ffmpeg路径
    ffmpeg: /usr/bin/ffmpeg
    # [必选 ] ffprobe路径， 一般安装ffmpeg就会自带， 一般跟ffmpeg在同一目录,用于查询文件的信息
    ffprobe: /usr/bin/ffprobe
    # [可选 ] 限制 ffmpeg 合并文件使用的线程数，间接限制cpu使用率， 默认2 限制到50%
    threads: 2
```
