### ISSUE TITLE
【技术咨询】云端录像无法查看下载

### ISSUE THREAD

**Issue by dpuact** [648540858/wvp-GB28181-pro#1638]
**环境信息:**

 - 1. 部署方式  **docker部署，docker-compose如下**
```yaml
  zlmediakit:
    container_name: zlmediakit
    image: zlmediakit/zlmediakit:master
    restart: always
    network_mode: host
    volumes:
      - ./config.ini:/opt/media/conf/config.ini
      - ./video:/opt/media/bin/www/record/
  wvp:
    image: wvp:2.7.3
    container_name: wvp
    network_mode: host
    volumes:
      - ./application.yml:/opt/app/conf/application.yml
      - ./logs:/opt/logs/
      - /etc/localtime:/etc/localtime
    restart: always
    environment:
      TZ: Asia/Shanghai
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      WVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      WVP_CONFIG:
    depends_on:
      - redis
      - zlmediakit
```
 - 2. 部署环境  **ubuntu 22.04**
 - 3. 端口开放情况 
 
 | 协议      | 端口            |
|-----------|-----------------|
| TCP       | 18083           |
| TCP       | 19351           |
| UDP/TCP   | 10332           |
| TCP       | 8001            |
| TCP       | 2554            |
| TCP       | 18000           |
| TCP       | 1443            |
| UDP       | 2554            |
| TCP       | 11935           |
| TCP/UDP       | 18081           |
| UDP       | 554             |
| TCP       | 1935            |
| UDP/TCP   | 10000           |
| UDP/TCP   | 30000-30500     |
| UDP/TCP   | 5060            |
| TCP       | 18080           |

 - 4. 是否是公网部署 **公网部署**
 - 5. 是否使用https **否**
 - 6. 方便的话提供下使用的设备品牌或平台  **大华**
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）**跟随master**

**内容描述:**

公网Docker部署WVP和ZLM，录像无法播放和下载，播放时黑屏，点击播放时请求出现401：
GET | http://公网IP:8001/index/api/downloadFile?file_path=/opt/media/bin/www/record/Home/1/2024-09-29/13-28-24-0.mp4
点击下载时，弹出页面显示Your ip is not allowed to access the service.

ZLM 配置：
allow_ip_range=::1,127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
我访问使用的电脑IP为192.168.0.100

**截图**  
![1727594491223](https://github.com/user-attachments/assets/a5bff77f-666c-4983-b840-0f13bf94044e)
![WX20240929-152154@2x](https://github.com/user-attachments/assets/5459979a-ded4-49f2-9b62-c69f3ffc51dc)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
