### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by luokeli59** [648540858/wvp-GB28181-pro#1823]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境 ubuntu 20.04-server
 - 3. 端口开放情况     ports:
      - "30000-30050:30000-30050/tcp"  # ZLM_PORT_RANGE_TCP
      - "30000-30050:30000-30050/udp"  # ZLM_PORT_RANGE_UDP
      - "9000:9000/tcp"                # ZLM_SRT_TCP
      - "9000:9000/udp"                # ZLM_SRT_TCP
      - "10000:10000/tcp"              # ZLM_RTP_PROXY_TCP
      - "10000:10000/udp"              # ZLM_RTP_PROXY_UDP
      - "554:554"                      # ZLM_RTSP_UDP
      - "554:554"                      # ZLM_RTSP_TCP
      - "8000:8000/tcp"                # ZLM_RTC_TCP
      - "8000:8000/udp"                # ZLM_RTC_UDP
      - "80:80"                        # ZLM_HTTP_TCP
      - "443:443"                      # ZLM_HTTPS_TCP
      - "1935:1935"                    # ZLM_RTMP_TCP
      - "5060:5060/tcp"                # WVP_SIP_SIGNALING_TCP
      - "5060:5060/udp"                # WVP_SIP_SIGNALING_UDP
      - "18080:18080"                  # WVP_SIP_HTTP_TCP
      - "18081:18081"                  # WVP_SIP_RECORD_ASSIST_TCP
 - 4. 是否是公网部署   否
 - 5. 是否使用https 否
 - 6. 接入设备/平台品牌  海康
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间  20250414
 - 9. 是否是4G设备接入 否

**描述错误**
描述下您遇到的问题
 使用docker compose 一键部署后 浏览器 访问 18080端口 查看 平台信息时： 发现编号是：
6.101130049e+19 字样 而且是容器的ip：192.168.1.56，问题1：能否正常显示 国标编号。问题2：能否显示宿主机ip
**如何复现**
有明确复现步骤的问题会很容易被解决
 cat docker-compose.yml
```
version: '3'
networks:
  wvp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_mvp
    networks:
      wvp_network:
        ipv4_address: 192.168.1.33
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
    ports:
      - 3306:3306
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: Kc@123456
      SQL_MODE: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      MYSQL_DATABASE: wvp
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initsql/:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql:rw
    healthcheck:
      start_period: 15s
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  redis:
    image: redis
    restart: always
    container_name: redis_mvp
    networks:
      wvp_network:
        ipv4_address: 192.168.1.63
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/etc/redis/redis_default.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis_default.conf --appendonly yes
  wvp:
    image: docker-wvp:latest
    restart: always
    container_name: zlm_sip_wvp
    networks:
      wvp_network:
        ipv4_address: 192.168.1.56
    ports:
      - "30000-30050:30000-30050/tcp"  # ZLM_PORT_RANGE_TCP
      - "30000-30050:30000-30050/udp"  # ZLM_PORT_RANGE_UDP
      - "9000:9000/tcp"                # ZLM_SRT_TCP
      - "9000:9000/udp"                # ZLM_SRT_TCP
      - "10000:10000/tcp"              # ZLM_RTP_PROXY_TCP
      - "10000:10000/udp"              # ZLM_RTP_PROXY_UDP
      - "554:554"                      # ZLM_RTSP_UDP
      - "554:554"                      # ZLM_RTSP_TCP
      - "8000:8000/tcp"                # ZLM_RTC_TCP
      - "8000:8000/udp"                # ZLM_RTC_UDP
      - "80:80"                        # ZLM_HTTP_TCP
      - "443:443"                      # ZLM_HTTPS_TCP
      - "1935:1935"                    # ZLM_RTMP_TCP
      - "5060:5060/tcp"                # WVP_SIP_SIGNALING_TCP
      - "5060:5060/udp"                # WVP_SIP_SIGNALING_UDP
      - "18080:18080"                  # WVP_SIP_HTTP_TCP
      - "18081:18081"                  # WVP_SIP_RECORD_ASSIST_TCP
    volumes:
      - ./zlmediakit/video:/opt/media/www/record/
      - ./zlmediakit/config/config.ini:/opt/media/config.ini
      - ./wvp_yml/assist-application-docker.yml:/opt/assist/config/application.yml
      - ./wvp_yml/wvp-application-docker.yml:/opt/wvp/config/application.yml
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./logs/media:/opt/media/log/
    environment:
      TZ: "Asia/Shanghai"
      # [必须修改] 本机的IP
      WVP_HOST: 192.168.1.56
      WVP_PWD: 12345678
      WVP_DOMAIN: 6101130049
      WVP_ID: 61011300490000000001
      REDIS_HOST: 192.168.1.63
      REDIS_PORT: 6379
      REDIS_DB: 6
      REDIS_PWD: Kc@123456
      MYSQL_HOST: 192.168.1.33
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PWD: Kc@123456
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      WVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      WVP_CONFIG:
    depends_on:
      - redis
      - mysql

```
**截图**  

![Image](https://github.com/user-attachments/assets/822393e6-7b25-41ef-abb1-914ae1f5851a)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
