### ISSUE TITLE
点播收流超时

### ISSUE THREAD

**Issue by desslee** [648540858/wvp-GB28181-pro#289]
**描述错误**
设备能注册、能刷新通道，点播收流超时
**如何复现**
可以复现，未能点播成功过

**预期行为**
可以点播

**截图**

![image](https://user-images.githubusercontent.com/13508661/147430249-d5d46fd2-f099-4a65-827e-efcac326b5d6.png)
截图里面的向 221.13.55.21:41746回复ack， 此IP是摄像头所在网络的IP
网络信息：
云服务器公网IP假设：106.53.17.123
内网IP：172.16.0.15
ZLM （dockerIP: 172.17.0.4）端口映射：（ 0.0.0.0:6080->80/tcp, :::6080->80/tcp, 0.0.0.0:10010->10000/tcp, 0.0.0.0:10010->10000/udp, :::10010->10000/tcp, :::10010->10000/udp ）

**环境信息:**
 - 1. 部署方式 ：在同一台云服务器上 wvp-pro 编译部署 +  zlm(docker)
 - 2. 部署环境 ：centos
 - 3. 端口开放情况 ：腾讯云服务器端口全开，zlm docker部署的
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 一开始尝试过使用本地电脑编译运行wvp+zlm的部署方式，使用nps穿透内网暴露端口，这种方式也是无法点播点刷新也会失败。后面部署到云服务器可以刷新但是无法点播。

以下几种配置方式都不能点播
配置方式1：
```
sip:
    ip:  172.16.0.15
    port: 5060
    domain: 4401020049
    id: 44010200492000000001
    password: admin123

#zlm 默认服务器配置
media:
    id: tx
    sdp-ip: 106.53.17.123
    stream-ip: 106.53.17.123
    ip: 172.17.0.4
    http-port: 80
    rtp-proxy-port: 10000
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    rtp:
        enable: false
        port-range: 30000,30500 # 端口范围
        send-port-range: 30000,30500 # 端口范围
    record-assist-port: 18081
```

配置方式2：
```
sip:
    ip:  172.16.0.15
    port: 5060
    domain: 4401020049
    id: 44010200492000000001
    password: admin123

#zlm 默认服务器配置
media:
    id: tx
    sdp-ip: 106.53.17.123
    stream-ip: 106.53.17.123
    # 172.16.0.15也不行
    ip: 106.53.17.123
    http-port: 6080
    rtp-proxy-port: 10010
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    rtp:
        enable: false
        port-range: 30000,30500 # 端口范围
        send-port-range: 30000,30500 # 端口范围
    record-assist-port: 18081
```

**Comment by openmynet** [comment]
点播超时最大的可能是 `gb28181客户端` 无法连接到 `zlmediakit` ； 所以请确保配置的media.ip 是 gb28181 Client 是可以访问到的IP
```
#1
GB28181.Client  --:5060--> wvp.server (5060: 数据端口)

#2
GB28181.Client  --:10010--> zlmediakit.server (10010: 固定视频流端口)[rtp-proxy-port: 10010]
# or
GB28181.Client  --:30000-30500--> zlmediakit.server  (30000-30500: 动态视频流端口)

#3
wvp.server -- :6080 --> zlmediakit.server (http-port: 6080, 视频播放及zlm管理端口)
```
```
sip:
    ip:  106.53.17.123
    port: 5060
    domain: 4401020049
    id: 44010200492000000001
    password: admin123

#zlm 默认服务器配置
media:
    id: tx
    ip: 106.53.17.123
    http-port: 6080
    rtp-proxy-port: 10010
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    rtp:
        enable: false
        port-range: 30000,30500 # 端口范围
        send-port-range: 30000,30500 # 端口范围
    record-assist-port: 18081

```
