### ISSUE TITLE
rtmp推流http只能使用m3u8播放

### ISSUE THREAD

**Issue by zgxsm** [648540858/wvp-GB28181-pro#548]
**描述错误**
搭建流媒体服务后使用obs推流，只能使用hls m3u8地址播放，flv无法播放，请问是否需要在zlm中开启相应的配置（使用国标级联的话可以注册但无法查询到视频流）

**如何复现**
1、搭建zlm和wvp
2、使用obs rtmp推流
3、使用/api/media/stream_info_by_app_and_stream查询流媒体信息
4、在wvp前端访问或者其他http播放插件访问视频流http://ip:port/live/livestream.flv  无法播放（同时步骤3中的其他播放地址也无法使用）

**预期行为**
stream_info_by_app_and_stream接口中的播放地址都可以使用

**截图**
![image](https://user-images.githubusercontent.com/27176642/179746469-f4e04355-442e-4eb5-bd23-2b9cfc23fbb9.png)

**环境信息:**
 - 1. 部署方式 ： 编译wvp-pro + zlm都是编译部署
 - 2. 部署环境 centos7
 - 3. 端口开放情况 80、1935、554、10000 
 - 4. 是否是公网部署： 否
 - 5. 是否使用https： 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 -
**WVP配置：**
```
spring:
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 127.0.0.1
        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: ?????????
        # [可选] 超时时间
        timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    datasource:
        # 使用mysql 打开23-28行注释， 删除29-36行
        name: ???????????
        url: ???????????????????
        username: ??????
        password: ??????????
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #name: eiot
        #url: jdbc:sqlite::resource:wvp.sqlite
        #username:
        #password:
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name:  org.sqlite.JDBC
        journal_mode: WAL
        synchronous: NORMAL
        transaction_mode: IMMEDIATE
        max-active: 1
        min-idle: 1

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.1.204
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: ???????????
    # [可选]
    id: ????????????????
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: 

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.1.204
    # [必须修改] zlm服务器的http.port
    http-port: 80
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: false
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 18081
# [可选] 日志配置, 一般不需要改
logging:
    file:
        name: logs/wvp.log
        max-history: 30
        max-size: 10MB
        total-size-cap: 300MB
    level:
        com.genersoft.iot: debug
        com.genersoft.iot.vmp.storager.dao: info
        com.genersoft.iot.vmp.gb28181: info

# [根据业务需求配置]
user-settings:
    # 推流直播是否录制
    record-push-live: true
    auto-apply-play: false

# 在线文档： swagger-ui（生产环境建议关闭）
swagger-ui:
    enabled: true

# 版本信息， 不需修改
version:
    version: "@project.version@"
    description: "@project.description@"
    artifact-id: "@project.artifactId@"
```
**zlm配置：**
```
[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
check_nvidia_dev=1
continue_push_ms=15000
enableVhost=0
enable_audio=1
enable_ffmpeg_log=0
flowThreshold=1024
fmp4_demand=0
hls_demand=1
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=18000
ts_demand=0
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000
[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=10.0
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.1.204:18080/index/hook/on_play
on_publish=http://192.168.1.204:18080/index/hook/on_publish
on_record_mp4=http://127.0.0.1:18081/api/record/on_record_mp4
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_server_keepalive=http://192.168.1.204:18080/index/hook/on_server_keepalive
on_server_started=http://192.168.1.204:18080/index/hook/on_server_started
on_shell_login=http://192.168.1.204:18080/index/hook/on_shell_login
on_stream_changed=http://192.168.1.204:18080/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.1.204:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.1.204:18080/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:14da5ab,branch:master,build time:Jul 19 2022 18:58:35)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=
[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1X,VP9,VP8
rembBitRate=0
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=0

[rtp]
audioMtuSize=600
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
g711a_pt=8
g711u_pt=0
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
timeoutSec=15
ts_pt=33
[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5
```
