### ISSUE TITLE
wvp配置https后，ZLM服务器无法推流，导致无法播放监控

### ISSUE THREAD

**Issue by skywsp** [648540858/wvp-GB28181-pro#56]
wvp配置https，修改application.yml中的sever，添加ssl配置:
```
# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080
    # springboot启用https
    ssl:
        key-store: classpath:client.pfx
        key-store-password: xxxxxxxx
        key-store-type: PKCS12
```
_注：zml的hook api需要改成https的_

然后播放监控时，ZLM服务器报错：
禁止RTP推流:[bad http status code]:400
![image](https://user-images.githubusercontent.com/25943305/108968650-008b7200-76bc-11eb-9cef-567824585cb3.png)
