### ISSUE TITLE
两个内网通过互联网级联，视频无法推送

### ISSUE THREAD

**Issue by supercooc** [648540858/wvp-GB28181-pro#571]
**
![WechatIMG460](https://user-images.githubusercontent.com/1592352/183621684-7a3ea4fb-1b8d-4027-83c0-1467ca46ba63.jpeg)
描述错误**
具体出现异常的情况如图，视频服务A上通过tcpdump抓包可以看到udp包已发，视频服务B 上无法抓到udp 包。 但是通过postman调用 直接先在视频服务B(zml) 开启接收端口，然后postman 调用视频服务A(zml) 来发送视频，此时视频服务B(zml) 可以收到推送的流，所有参数与wvp调用zml参数一致。

**预期行为**
我实在无法想清楚为啥 手动调用可以推流， wvp 调用就无法推流
**环境信息:**
 1 两边都是 centos 7

**Comment by supercooc** [comment]
两边都在内网服务器部署，通过端口映射udp 5060, 30000-30500 来开放端口

**Comment by Smallwhitepig** [comment]
这些都是基础问题,感觉会变成问答贴
1 映射的收发流是否映射TCP UDP ？
2 如果1没问题 那就从服务器两端同时捉包

**Comment by supercooc** [comment]
> 这些都是基础问题,感觉会变成问答贴 1 映射的收发流是否映射TCP UDP ？ 2 如果1没问题 那就从服务器两端同时捉包
1. 只用到了udp， 只映射udp端口，映射只做收流
2. 两端抓包也说了，sip包都两边都有，视频包只有在发送端看到，接收端没有

**Comment by supercooc** [comment]
> 先说下你的怎么用互联网打通两个服务的

两边都是在路由器上做nat 映射啊，开5060和 30000-30500的udp 端口到内网服务器

**Comment by 648540858** [comment]
1. 哪边是作为上级的，
2. 你的上级wvp中的media配置，是否配置了正确公网IP，如果不确定就把media配置贴一下，记得放在```里

**Comment by supercooc** [comment]
右边的B 是上级 
```
media:
    id: MEHaYNpdyLPuMkTm
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.30.185
    # [必须修改] zlm服务器的http.port
    http-port: 8091
    sdp-ip: 39.174.*.171
    stream-ip: 39.174.*.171
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 18081
```
