### ISSUE TITLE
国标接入可以播放  拉流代理无法播放

### ISSUE THREAD

**Issue by yh4922** [648540858/wvp-GB28181-pro#596]
**描述错误**
拉流代理在网页上无法播放， 国标的可以
使用vlc 播放 rtsp 国标的也正常  

**截图**
![image](https://user-images.githubusercontent.com/18353610/187893447-67ab23aa-8b22-4eda-a690-82b2854d2532.png)
![image](https://user-images.githubusercontent.com/18353610/187893561-ace209dd-53fd-4bf1-b6aa-0a9e3d6af529.png)
![image](https://user-images.githubusercontent.com/18353610/187893760-77f864c2-fa58-436d-92e3-63a9649df08f.png)
![image](https://user-images.githubusercontent.com/18353610/187894457-c66a1e39-9276-491c-a0ab-8b2ed41828cd.png)
ZLM节点显示正常

**环境信息:**
部署方式 在docker 容器中编译 ZLMediaKit 和 WVP-PRO
ZLMediaKit  和 WVP-PRO 运行在同一个容器中 镜像为 ubuntu:20.04
按照wiki编译
```
root@pc-MS-7D17:/ZLMediaKit/release/linux/Debug# ./MediaServer -v
编译日期: 2022-09-01 15:15:31
当前git分支: master
当前git hash值: 679c798
```

<details><summary>ZLMediaKit 配置（点击查看）</summary>
[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
check_nvidia_dev=1
continue_push_ms=3000
enableVhost=0
enable_audio=1
enable_ffmpeg_log=0
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=FQ3TF8yT83wh5Wvz
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=10000
ts_demand=0
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=10.0
enable=1
on_flow_report=http://192.168.18.60:18080/index/hook/on_flow_report
on_http_access=http://192.168.18.60:18080/index/hook/on_http_access
on_play=http://192.168.18.60:18080/index/hook/on_play
on_publish=http://192.168.18.60:18080/index/hook/on_publish
on_record_mp4=
on_record_ts=http://192.168.18.60:18080/index/hook/on_record_ts
on_rtsp_auth=http://192.168.18.60:18080/index/hook/on_rtsp_auth
on_rtsp_realm=http://192.168.18.60:18080/index/hook/on_rtsp_realm
on_send_rtp_stopped=https://127.0.0.1/index/hook/on_send_rtp_stopped
on_server_keepalive=http://192.168.18.60:18080/index/hook/on_server_keepalive
on_server_started=http://192.168.18.60:18080/index/hook/on_server_started
on_shell_login=http://192.168.18.60:18080/index/hook/on_shell_login
on_stream_changed=http://192.168.18.60:18080/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.18.60:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.18.60:18080/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:679c798,branch:master,build time:Sep  1 2022 13:12:18)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
mp4_as_player=0
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1X,VP9,VP8
rembBitRate=0
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=0

[rtp]
audioMtuSize=600
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
g711a_pt=8
g711u_pt=0
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-30500
ps_pt=96
timeoutSec=15
ts_pt=33

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5
</details>

<details><summary>WVP_PRO配置（点击查看）</summary>
spring:
    # [可选]上传文件大小限制
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 127.0.0.1
        # [必须修改] 端口号
        port: 6389 
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        # password: face2020
        # [可选] 超时时间
        timeout: 10000
        # mysql数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
        username: root
        password: 123456
        druid:
            initialSize: 10                       # 连接池初始化连接数
            maxActive: 200                        # 连接池最大连接数
            minIdle: 5                            # 连接池最小空闲连接数
            maxWait: 60000                        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
            keepAlive: true                       # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
            validationQuery: select 1             # 检测连接是否有效sql，要求是查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
            testWhileIdle: true                   # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            testOnBorrow: false                   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnReturn: false                   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            poolPreparedStatements: false         # 是否開啟PSCache，並且指定每個連線上PSCache的大小
            timeBetweenEvictionRunsMillis: 60000  # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連線，單位是毫秒
            minEvictableIdleTimeMillis: 300000    # 配置一個連線在池中最小生存的時間，單位是毫秒
            filters: stat,slf4j             # 配置监控统计拦截的filters，监控统计用的filter:sta, 日志用的filter:log4j
            useGlobalDataSourceStat: true         # 合并多个DruidDataSource的监控数据
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
            #stat-view-servlet.url-pattern: /admin/druid/*

#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.18.60
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4401020049
    # [可选]
    id: 44010200492000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: admin123

#zlm 默认服务器配置
media:
    id: FQ3TF8yT83wh5Wvz
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.18.60
    # [必须修改] zlm服务器的http.port
    http-port: 80
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 0

# 定制信息配置
user-settings:
    # 自动点播
    auto-apply-play: true
    # 不鉴权的接口
    interface-authentication-excludes:
        - /api/play/start/** # 获取播放国标播放列表接口
        - /api/proxy/save/   # 保存代理接口

# [可选] 日志配置, 一般不需要改
logging:
    config: classpath:logback-spring-local.xml

# 版本信息， 不需修改
version:
    version: "@project.version@"
    description: "@project.description@"
    artifact-id: "@project.artifactId@"
</details>

**Comment by yh4922** [comment]
> 补充部署方式

docker容器启动
``` bash
docker run \
  -e TZ="Asia/Shanghai" \
  --privileged \
  --network host \
  --ipc=host \
  --name wvp \
  -v /media_conf:/media_conf \
  -v /etc/localtime:/etc/localtime \
  ubuntu:20.04 sh /media_conf/install.sh
```

<details>
<summary>安装脚本：/media_conf/install.sh</summary>

```sh
#!/bin/bash
# 验证 /MediaInstall.lock文件是否存在
if [ -f /MediaInstall.lock ]; then
  echo "MediaInstall.lock文件已存在，请确认是否已安装！"
else 
  echo "export  LANG=C.UTF-8" >> /etc/profile && echo "export  LC_ALL=C.UTF-8" >> /etc/profile && source /etc/profile

  # 切换源
  sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

  # 更新软件列表
  apt-get update -y && apt-get upgrade -y

  # 安装依赖
  apt-get install -y openjdk-11-jre git maven nodejs npm curl vim \
      build-essential cmake libssl-dev libsdl-dev libavcodec-dev libavutil-dev ffmpeg

  # 安装libsrtp
  cd / 
  curl -o libsrtp-2.3.0.tar.gz https://res.cvvii.com/libsrtp-2.3.0.tar.gz
  tar -xvzf libsrtp-2.3.0.tar.gz && rm -rf libsrtp-2.3.0.tar.gz

  cd /libsrtp-2.3.0
  ./configure --enable-openssl
  make -j8 && make install

  # 编译ZLMediaKit
  cd /
  git clone --depth 1 https://gitee.com/xia-chu/ZLMediaKit
  cd /ZLMediaKit
  git submodule update --init

  mkdir build && cd build
  cmake .. -DENABLE_WEBRTC=true
  cmake --build . --target MediaServer

  # 编译WVP-PRO
  cd /
  git clone https://gitee.com/pan648540858/wvp-GB28181-pro.git
  cd /wvp-GB28181-pro/web_src/
  # 打包前端
  npm --registry=https://registry.npm.taobao.org install
  npm run build
  # 打包项目
  cd /wvp-GB28181-pro/
  mvn package
  
  # 写入安装锁文件
  touch /MediaInstall.lock
fi

#启动程序
nohup /ZLMediaKit/release/linux/Debug/MediaServer -c /media_conf/config.ini -d & java -jar /wvp-GB28181-pro/target/wvp-pro-*.jar --spring.config.location=/media_conf/application-dev.yml
```
</details>

<details>
<summary>ZLM配置文件：/media_conf/config.ini</summary>

```ini
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
check_nvidia_dev=1
continue_push_ms=3000
enableVhost=0
enable_audio=1
enable_ffmpeg_log=0
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=FQ3TF8yT83wh5Wvz
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=10000
ts_demand=0
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=10.0
enable=1
on_flow_report=http://192.168.18.60:18080/index/hook/on_flow_report
on_http_access=http://192.168.18.60:18080/index/hook/on_http_access
on_play=http://192.168.18.60:18080/index/hook/on_play
on_publish=http://192.168.18.60:18080/index/hook/on_publish
on_record_mp4=
on_record_ts=http://192.168.18.60:18080/index/hook/on_record_ts
on_rtsp_auth=http://192.168.18.60:18080/index/hook/on_rtsp_auth
on_rtsp_realm=http://192.168.18.60:18080/index/hook/on_rtsp_realm
on_send_rtp_stopped=http://127.0.0.1:18080/index/hook/on_send_rtp_stopped
on_server_keepalive=http://192.168.18.60:18080/index/hook/on_server_keepalive
on_server_started=http://192.168.18.60:18080/index/hook/on_server_started
on_shell_login=http://192.168.18.60:18080/index/hook/on_shell_login
on_stream_changed=http://192.168.18.60:18080/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.18.60:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.18.60:18080/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:679c798,branch:master,build time:Sep  1 2022 13:12:18)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
mp4_as_player=0
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1X,VP9,VP8
rembBitRate=0
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=0

[rtp]
audioMtuSize=600
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
g711a_pt=8
g711u_pt=0
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-30500
ps_pt=96
timeoutSec=15
ts_pt=33

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---
```
</details>

<details>
<summary>WVP-PRO配置：/media_conf/application-dev.yml</summary>

```yml
spring:
    # [可选]上传文件大小限制
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 127.0.0.1
        # [必须修改] 端口号
        port: 6389 
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        # password: face2020
        # [可选] 超时时间
        timeout: 10000
        # mysql数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
        username: root
        password: 123456
        druid:
            initialSize: 10                       # 连接池初始化连接数
            maxActive: 200                        # 连接池最大连接数
            minIdle: 5                            # 连接池最小空闲连接数
            maxWait: 60000                        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
            keepAlive: true                       # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
            validationQuery: select 1             # 检测连接是否有效sql，要求是查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
            testWhileIdle: true                   # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            testOnBorrow: false                   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnReturn: false                   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            poolPreparedStatements: false         # 是否開啟PSCache，並且指定每個連線上PSCache的大小
            timeBetweenEvictionRunsMillis: 60000  # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連線，單位是毫秒
            minEvictableIdleTimeMillis: 300000    # 配置一個連線在池中最小生存的時間，單位是毫秒
            filters: stat,slf4j             # 配置监控统计拦截的filters，监控统计用的filter:sta, 日志用的filter:log4j
            useGlobalDataSourceStat: true         # 合并多个DruidDataSource的监控数据
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
            #stat-view-servlet.url-pattern: /admin/druid/*

#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.18.60
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4401020049
    # [可选]
    id: 44010200492000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: admin123

#zlm 默认服务器配置
media:
    id: FQ3TF8yT83wh5Wvz
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.18.60
    # [必须修改] zlm服务器的http.port
    http-port: 80
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 0

# 定制信息配置
user-settings:
    # 自动点播
    auto-apply-play: true
    # 不鉴权的接口
    interface-authentication-excludes:
        - /api/play/start/** # 获取播放国标播放列表接口
        - /api/proxy/save/   # 保存代理接口

# [可选] 日志配置, 一般不需要改
logging:
    config: classpath:logback-spring-local.xml

# 版本信息， 不需修改
version:
    version: "@project.version@"
    description: "@project.description@"
    artifact-id: "@project.artifactId@"
```
</details>


mongo 和 redis 部署在同一台机器上的另外个容器上
```bash
docker run  --name mysqldb \
    -p 3306:3306 \
    -v /media_conf:/media_conf \
    -e MYSQL_ROOT_PASSWORD=123456 \
    -d mysql:latest
```
```bash
docker run --name redis -p 6389:6379 -d redis
```
