### ISSUE TITLE
[BUG]云上部署服务不能正常播放视频

### ISSUE THREAD

**Issue by eanfs** [648540858/wvp-GB28181-pro#773]
**描述错误**
云上部署服务，IVS1800不能正常播放视频，抓包发现在有些SIP 命令使用了服务器内网的IP，

**如何复现**
云服务器在VPC网络下部署服务器IP 10.10.0.136

在云端部署申请EIP 123.60.XXX.XX 绑定到服务器

 如果sip.ip 设置为 10.10.0.136 ，WVP服务可以正常启动，但视频不能播放

 如果sip.ip 设置为 123.60.XXX.XX ，WVP服务可以不能正常启动，查看启动错误日志，好像网卡没有123.60.XXX.XX 的设备

**应该如果配置与修改？**

**预期行为**

云上部署服务能正常播放视频

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 是
 - 5. 是否使用https https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by zhuuvzhi** [comment]
这是一条很重要的消息，居然没有在README里面写清楚：
**阿里云的专有网络默认是不能支持SIP的，需要去专有网络设置EIP可见才可能。**

**Comment by 648540858** [comment]
把这几个ip自行配置下
```
media:
    # [必须修改] zlm服务器的内网IP
    ip: 127.0.0.1
    # [可选] 返回流地址时的ip，置空使用 media.ip
    stream-ip: 123.60.XXX.XX
    # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
    sdp-ip: 123.60.XXX.XX
    # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
    hook-ip: 127.0.0.1
```
如果你的zlm和wvp是部署在一起，那么可以参考我发的配置，sip.ip配置为10.10.0.136 即可
