### ISSUE TITLE
升级到最新版来的配置问题

### ISSUE THREAD

**Issue by tongwoo** [648540858/wvp-GB28181-pro#818]
今天升级到了最新版，使用中出现了不知道怎么解决的问题，还请作者能帮助一下，感激不尽

**描述错误**

在使用 `2.3.2` 版本的时候，`application.yml` 配置中

```yml
# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP, 必须是网卡上的IP，用于sip下协议栈监听ip，如果监听所有设置为0.0.0.0
    monitor-ip: 0.0.0.0
    # [必须修改] 本机的IP
    ip: 127.0.0.1
    # [可选] 28181服务监听的端口
    port: 5060
```
`sip` 配置段中会提供一个监听ip和本机ip，在当前最新版本中，在 `src/main/resources` 目录中发现其配置变为了

```yml
# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 127.0.0.1
    # [可选] 没有任何业务需求，仅仅是在前端展示的时候用
    show-ip: 192.168.0.100
    # [可选] 28181服务监听的端口
    port: 5060
```

少了 `monitor-ip`，因为我是用在 `docker` 环境中，经过排查，会导致如下问题：

1、如果 `sip.ip` 配置成 `127.0.0.1`，`wvp` 虽然监听了 `5060` 端口，但无法接受并处理 `sip` 请求
2、如果 `sip.ip` 配置成 `0.0.0.0`，`wvp` 在发送请求播放的时候会导致命令发送失败并抛出 `illegal character hostname` 之类的错误

**如何复现**

如上一步所示

**预期行为**

希望能恢复 `monitor-ip` 的选项

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 都是docker
 - 2. 部署环境 windows / ubuntu/ centos ...
 windows、macos
 - 3. 端口开放情况
 - 4. 是否是公网部署
 否
 - 5. 是否使用https
 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
