### ISSUE TITLE
【技术咨询】wvp绑定5060端口时，只能绑定当前机器存在的IP，报错“SIP服务启动失败,请检查端口是否被占用或者ip是否正确”

### ISSUE THREAD

**Issue by phoenixZZZ** [648540858/wvp-GB28181-pro#826]
**环境信息:**

 - 1. 部署方式: zlm(docker) + 编译wvp-pro/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况: 5060 18080 ZLM的所有端口
 - 4. 是否是公网部署： 是
 - 5. 是否使用https： 否
 - 6. 方便的话提供下使用的设备品牌或平台： 海康摄像头
 - 7. 你做过哪些尝试：尝试在阿里云部署wvp 
 - 8. 代码更新时间：master分支最新提交

**内容描述:**
我在测试验证中发现，wvp绑定5060端口时，只能绑定当前机器存在的IP
以阿里云服务器举例，外网地址123.0.0.0，内网地址：127.0.0.0；我启动wvp时只能绑定127.0.0.0的地址
但如果我绑定127.0.0.0的地址的话，虽然123.0.0.0可以正常访问，127.0.0.0绑定的5060端口
但是，我通过设备，没有办法完成注册。
但如果我绑定123.0.0.0地址的5060端口，wvp又无法完成绑定操作报

```
[Sip Server] tcp://{}:{} SIP服务启动失败,请检查端口是否被占用或者ip是否正确
```

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by user0723** [comment]
我也有同样问题，解决了吗

**Comment by 648540858** [comment]
sip.ip 写IP的目的时为例告诉WVP你要监听哪张网卡，而不是跟IP有什么关系，
1. sip.ip可以写多个，逗号分隔，对应多张网卡。
2. 监听127.0.0.1说明你对注释里“本机的IP”不明白，你真的觉得127.0.0.1算是本机的IP吗，其他设备根据这个IP访问到吗
```
sip:
    # [必须修改] 本机的IP
    ip: 192.168.0.100
```
3. 如果你实在不知道写什么，就写`0.0.0.0`吧，大部分的情况都是可以的。

**Comment by phoenixZZZ** [comment]
0.0.0.0的话，阿里云还可以，但是docker下面使用的话就不好使，我使用的是bridge网络，好像宿主机的IP始终用不到；
```
# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: ${SIP_IP:192.168.2.153}
    # [可选] 28181服务监听的端口
    port: ${SIP_PORT:5060}
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: ${SIP_DOMAIN:4401020049}
    # [可选]
    id: ${SIP_ID:44010200492000000001}
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: ${SIP_PWD:admin123}
```
docker-compose.yml
```
...
      SIP_IP: 0.0.0.0
      SIP_PORT: 5060
      SIP_DOMAIN: 4401020049
      SIP_ID: 44010200492000000001
      SIP_PWD: admin123
...
```

docker版本的如何使用外部IP的，如何解决，请教一下
